// <auto-generated />
namespace FifteenGame.DataAccess.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class GameMinorFixes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GameMinorFixes));
        
        string IMigrationMetadata.Id
        {
            get { return "202502250639454_GameMinorFixes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
