// <auto-generated />
namespace FifteenGame.DataAccess.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class CheckersTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CheckersTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202606251527171_CheckersTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
