// <auto-generated />
namespace FifteenGame.DataAccess.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Links : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Links));
        
        string IMigrationMetadata.Id
        {
            get { return "202511241208008_Links"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
