// <auto-generated />
namespace FifteenGame.DataAcces.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Match3Game : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Match3Game));
        
        string IMigrationMetadata.Id
        {
            get { return "202605200053242_Match3Game"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
