namespace Calculator {
    partial class CalculatorForm {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing) {
            if (disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent() {
            DisplayLabel = new Label();
            ExpressionLabel = new Label();
            Digit7Button = new RoundedButton();
            Digit8Button = new RoundedButton();
            Digit9Button = new RoundedButton();
            Digit4Button = new RoundedButton();
            Digit5Button = new RoundedButton();
            Digit6Button = new RoundedButton();
            Digit1Button = new RoundedButton();
            Digit2Button = new RoundedButton();
            Digit3Button = new RoundedButton();
            Digit0Button = new RoundedButton();
            ClearButton = new RoundedButton();
            SubtractButton = new RoundedButton();
            AddButton = new RoundedButton();
            DivideButton = new RoundedButton();
            MultiplyButton = new RoundedButton();
            EqualButton = new RoundedButton();
            SineButton = new RoundedButton();
            TrigMenuButton = new RoundedButton();
            MemoryStoreButton = new RoundedButton();
            MemoryRecallButton = new RoundedButton();
            DecimalButton = new RoundedButton();
            ChangeSignButton = new RoundedButton();
            SquareButton = new RoundedButton();
            SquareRootButton = new RoundedButton();
            PercentButton = new RoundedButton();
            SuspendLayout();

            DisplayLabel.BackColor = Color.FromArgb(100, 40, 40, 40);
            DisplayLabel.BorderStyle = BorderStyle.FixedSingle;
            DisplayLabel.Font = new Font("Segoe UI", 24F, FontStyle.Bold);
            DisplayLabel.ForeColor = Color.White;
            DisplayLabel.Location = new Point(16, 69);
            DisplayLabel.Margin = new Padding(4, 0, 4, 0);
            DisplayLabel.Name = "DisplayLabel";
            DisplayLabel.Size = new Size(681, 91);
            DisplayLabel.TabIndex = 1;
            DisplayLabel.Text = "0";
            DisplayLabel.TextAlign = ContentAlignment.MiddleRight;

            ExpressionLabel.BackColor = Color.FromArgb(100, 40, 40, 40);
            ExpressionLabel.BorderStyle = BorderStyle.FixedSingle;
            ExpressionLabel.Font = new Font("Segoe UI", 12F);
            ExpressionLabel.ForeColor = Color.FromArgb(220, 220, 220);
            ExpressionLabel.Location = new Point(16, 15);
            ExpressionLabel.Margin = new Padding(4, 0, 4, 0);
            ExpressionLabel.Name = "ExpressionLabel";
            ExpressionLabel.Size = new Size(681, 45);
            ExpressionLabel.TabIndex = 0;
            ExpressionLabel.TextAlign = ContentAlignment.MiddleRight;

            Digit7Button.BackColor = Color.FromArgb(50, 50, 50);
            Digit7Button.FlatStyle = FlatStyle.Flat;
            Digit7Button.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            Digit7Button.ForeColor = Color.White;
            Digit7Button.Location = new Point(16, 177);
            Digit7Button.Margin = new Padding(4, 5, 4, 5);
            Digit7Button.Name = "Digit7Button";
            Digit7Button.Size = new Size(107, 123);
            Digit7Button.TabIndex = 2;
            Digit7Button.Text = "7";
            Digit7Button.UseVisualStyleBackColor = false;
            Digit7Button.Click += DigitButton_Click;

            Digit8Button.BackColor = Color.FromArgb(50, 50, 50);
            Digit8Button.FlatStyle = FlatStyle.Flat;
            Digit8Button.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            Digit8Button.ForeColor = Color.White;
            Digit8Button.Location = new Point(131, 177);
            Digit8Button.Margin = new Padding(4, 5, 4, 5);
            Digit8Button.Name = "Digit8Button";
            Digit8Button.Size = new Size(107, 123);
            Digit8Button.TabIndex = 3;
            Digit8Button.Text = "8";
            Digit8Button.UseVisualStyleBackColor = false;
            Digit8Button.Click += DigitButton_Click;

            Digit9Button.BackColor = Color.FromArgb(50, 50, 50);
            Digit9Button.FlatStyle = FlatStyle.Flat;
            Digit9Button.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            Digit9Button.ForeColor = Color.White;
            Digit9Button.Location = new Point(245, 177);
            Digit9Button.Margin = new Padding(4, 5, 4, 5);
            Digit9Button.Name = "Digit9Button";
            Digit9Button.Size = new Size(107, 123);
            Digit9Button.TabIndex = 4;
            Digit9Button.Text = "9";
            Digit9Button.UseVisualStyleBackColor = false;
            Digit9Button.Click += DigitButton_Click;

            Digit4Button.BackColor = Color.FromArgb(50, 50, 50);
            Digit4Button.FlatStyle = FlatStyle.Flat;
            Digit4Button.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            Digit4Button.ForeColor = Color.White;
            Digit4Button.Location = new Point(16, 309);
            Digit4Button.Margin = new Padding(4, 5, 4, 5);
            Digit4Button.Name = "Digit4Button";
            Digit4Button.Size = new Size(107, 123);
            Digit4Button.TabIndex = 5;
            Digit4Button.Text = "4";
            Digit4Button.UseVisualStyleBackColor = false;
            Digit4Button.Click += DigitButton_Click;

            Digit5Button.BackColor = Color.FromArgb(50, 50, 50);
            Digit5Button.FlatStyle = FlatStyle.Flat;
            Digit5Button.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            Digit5Button.ForeColor = Color.White;
            Digit5Button.Location = new Point(131, 309);
            Digit5Button.Margin = new Padding(4, 5, 4, 5);
            Digit5Button.Name = "Digit5Button";
            Digit5Button.Size = new Size(107, 123);
            Digit5Button.TabIndex = 6;
            Digit5Button.Text = "5";
            Digit5Button.UseVisualStyleBackColor = false;
            Digit5Button.Click += DigitButton_Click;

            Digit6Button.BackColor = Color.FromArgb(50, 50, 50);
            Digit6Button.FlatStyle = FlatStyle.Flat;
            Digit6Button.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            Digit6Button.ForeColor = Color.White;
            Digit6Button.Location = new Point(245, 309);
            Digit6Button.Margin = new Padding(4, 5, 4, 5);
            Digit6Button.Name = "Digit6Button";
            Digit6Button.Size = new Size(107, 123);
            Digit6Button.TabIndex = 7;
            Digit6Button.Text = "6";
            Digit6Button.UseVisualStyleBackColor = false;
            Digit6Button.Click += DigitButton_Click;

            Digit1Button.BackColor = Color.FromArgb(50, 50, 50);
            Digit1Button.FlatStyle = FlatStyle.Flat;
            Digit1Button.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            Digit1Button.ForeColor = Color.White;
            Digit1Button.Location = new Point(16, 442);
            Digit1Button.Margin = new Padding(4, 5, 4, 5);
            Digit1Button.Name = "Digit1Button";
            Digit1Button.Size = new Size(107, 123);
            Digit1Button.TabIndex = 8;
            Digit1Button.Text = "1";
            Digit1Button.UseVisualStyleBackColor = false;
            Digit1Button.Click += DigitButton_Click;

            Digit2Button.BackColor = Color.FromArgb(50, 50, 50);
            Digit2Button.FlatStyle = FlatStyle.Flat;
            Digit2Button.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            Digit2Button.ForeColor = Color.White;
            Digit2Button.Location = new Point(131, 442);
            Digit2Button.Margin = new Padding(4, 5, 4, 5);
            Digit2Button.Name = "Digit2Button";
            Digit2Button.Size = new Size(107, 123);
            Digit2Button.TabIndex = 9;
            Digit2Button.Text = "2";
            Digit2Button.UseVisualStyleBackColor = false;
            Digit2Button.Click += DigitButton_Click;

            Digit3Button.BackColor = Color.FromArgb(50, 50, 50);
            Digit3Button.FlatStyle = FlatStyle.Flat;
            Digit3Button.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            Digit3Button.ForeColor = Color.White;
            Digit3Button.Location = new Point(245, 442);
            Digit3Button.Margin = new Padding(4, 5, 4, 5);
            Digit3Button.Name = "Digit3Button";
            Digit3Button.Size = new Size(107, 123);
            Digit3Button.TabIndex = 10;
            Digit3Button.Text = "3";
            Digit3Button.UseVisualStyleBackColor = false;
            Digit3Button.Click += DigitButton_Click;

            Digit0Button.BackColor = Color.FromArgb(50, 50, 50);
            Digit0Button.FlatStyle = FlatStyle.Flat;
            Digit0Button.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            Digit0Button.ForeColor = Color.White;
            Digit0Button.Location = new Point(16, 574);
            Digit0Button.Margin = new Padding(4, 5, 4, 5);
            Digit0Button.Name = "Digit0Button";
            Digit0Button.Size = new Size(107, 123);
            Digit0Button.TabIndex = 11;
            Digit0Button.Text = "0";
            Digit0Button.UseVisualStyleBackColor = false;
            Digit0Button.Click += DigitButton_Click;

            ClearButton.BackColor = Color.FromArgb(200, 50, 50);
            ClearButton.FlatStyle = FlatStyle.Flat;
            ClearButton.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            ClearButton.ForeColor = Color.White;
            ClearButton.Location = new Point(360, 177);
            ClearButton.Margin = new Padding(4, 5, 4, 5);
            ClearButton.Name = "ClearButton";
            ClearButton.Size = new Size(107, 123);
            ClearButton.TabIndex = 12;
            ClearButton.Text = "C";
            ClearButton.UseVisualStyleBackColor = false;
            ClearButton.Click += ClearButton_Click;

            SubtractButton.BackColor = Color.FromArgb(70, 70, 70);
            SubtractButton.FlatStyle = FlatStyle.Flat;
            SubtractButton.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            SubtractButton.ForeColor = Color.White;
            SubtractButton.Location = new Point(475, 309);
            SubtractButton.Margin = new Padding(4, 5, 4, 5);
            SubtractButton.Name = "SubtractButton";
            SubtractButton.Size = new Size(107, 123);
            SubtractButton.TabIndex = 13;
            SubtractButton.Text = "-";
            SubtractButton.UseVisualStyleBackColor = false;
            SubtractButton.Click += OperationButton_Click;

            AddButton.BackColor = Color.FromArgb(70, 70, 70);
            AddButton.FlatStyle = FlatStyle.Flat;
            AddButton.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            AddButton.ForeColor = Color.White;
            AddButton.Location = new Point(475, 177);
            AddButton.Margin = new Padding(4, 5, 4, 5);
            AddButton.Name = "AddButton";
            AddButton.Size = new Size(107, 123);
            AddButton.TabIndex = 14;
            AddButton.Text = "+";
            AddButton.UseVisualStyleBackColor = false;
            AddButton.Click += OperationButton_Click;

            DivideButton.BackColor = Color.FromArgb(70, 70, 70);
            DivideButton.FlatStyle = FlatStyle.Flat;
            DivideButton.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            DivideButton.ForeColor = Color.White;
            DivideButton.Location = new Point(475, 442);
            DivideButton.Margin = new Padding(4, 5, 4, 5);
            DivideButton.Name = "DivideButton";
            DivideButton.Size = new Size(107, 123);
            DivideButton.TabIndex = 15;
            DivideButton.Text = "/";
            DivideButton.UseVisualStyleBackColor = false;
            DivideButton.Click += OperationButton_Click;

            MultiplyButton.BackColor = Color.FromArgb(70, 70, 70);
            MultiplyButton.FlatStyle = FlatStyle.Flat;
            MultiplyButton.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            MultiplyButton.ForeColor = Color.White;
            MultiplyButton.Location = new Point(475, 574);
            MultiplyButton.Margin = new Padding(4, 5, 4, 5);
            MultiplyButton.Name = "MultiplyButton";
            MultiplyButton.Size = new Size(107, 123);
            MultiplyButton.TabIndex = 16;
            MultiplyButton.Text = "*";
            MultiplyButton.UseVisualStyleBackColor = false;
            MultiplyButton.Click += OperationButton_Click;

            EqualButton.BackColor = Color.FromArgb(0, 120, 215);
            EqualButton.FlatStyle = FlatStyle.Flat;
            EqualButton.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            EqualButton.ForeColor = Color.White;
            EqualButton.Location = new Point(360, 574);
            EqualButton.Margin = new Padding(4, 5, 4, 5);
            EqualButton.Name = "EqualButton";
            EqualButton.Size = new Size(107, 123);
            EqualButton.TabIndex = 17;
            EqualButton.Text = "=";
            EqualButton.UseVisualStyleBackColor = false;
            EqualButton.Click += EqualButton_Click;

            SineButton.BackColor = Color.FromArgb(0, 150, 136);
            SineButton.FlatStyle = FlatStyle.Flat;
            SineButton.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            SineButton.ForeColor = Color.White;
            SineButton.Location = new Point(360, 442);
            SineButton.Margin = new Padding(4, 5, 4, 5);
            SineButton.Name = "SineButton";
            SineButton.Size = new Size(107, 123);
            SineButton.TabIndex = 19;
            SineButton.Text = "sin";
            SineButton.UseVisualStyleBackColor = false;
            SineButton.Click += FunctionButton_Click;

            TrigMenuButton.BackColor = Color.FromArgb(100, 100, 100);
            TrigMenuButton.FlatStyle = FlatStyle.Flat;
            TrigMenuButton.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            TrigMenuButton.ForeColor = Color.White;
            TrigMenuButton.Location = new Point(427, 442);
            TrigMenuButton.Margin = new Padding(4, 5, 4, 5);
            TrigMenuButton.Name = "TrigMenuButton";
            TrigMenuButton.Size = new Size(40, 46);
            TrigMenuButton.TabIndex = 20;
            TrigMenuButton.Text = "▼";
            TrigMenuButton.UseVisualStyleBackColor = false;
            TrigMenuButton.Click += TrigMenuButton_Click;

            MemoryStoreButton.BackColor = Color.FromArgb(0, 150, 136);
            MemoryStoreButton.FlatStyle = FlatStyle.Flat;
            MemoryStoreButton.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            MemoryStoreButton.ForeColor = Color.White;
            MemoryStoreButton.Location = new Point(590, 575);
            MemoryStoreButton.Margin = new Padding(4, 5, 4, 5);
            MemoryStoreButton.Name = "MemoryStoreButton";
            MemoryStoreButton.Size = new Size(107, 122);
            MemoryStoreButton.TabIndex = 21;
            MemoryStoreButton.Text = "MS";
            MemoryStoreButton.UseVisualStyleBackColor = false;
            MemoryStoreButton.Click += FunctionButton_Click;

            MemoryRecallButton.BackColor = Color.FromArgb(0, 150, 136);
            MemoryRecallButton.FlatStyle = FlatStyle.Flat;
            MemoryRecallButton.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            MemoryRecallButton.ForeColor = Color.White;
            MemoryRecallButton.Location = new Point(590, 442);
            MemoryRecallButton.Margin = new Padding(4, 5, 4, 5);
            MemoryRecallButton.Name = "MemoryRecallButton";
            MemoryRecallButton.Size = new Size(107, 123);
            MemoryRecallButton.TabIndex = 22;
            MemoryRecallButton.Text = "MR";
            MemoryRecallButton.UseVisualStyleBackColor = false;
            MemoryRecallButton.Click += FunctionButton_Click;

            DecimalButton.BackColor = Color.FromArgb(50, 50, 50);
            DecimalButton.FlatStyle = FlatStyle.Flat;
            DecimalButton.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            DecimalButton.ForeColor = Color.White;
            DecimalButton.Location = new Point(131, 574);
            DecimalButton.Margin = new Padding(4, 5, 4, 5);
            DecimalButton.Name = "DecimalButton";
            DecimalButton.Size = new Size(107, 123);
            DecimalButton.TabIndex = 23;
            DecimalButton.Text = ".";
            DecimalButton.UseVisualStyleBackColor = false;
            DecimalButton.Click += FunctionButton_Click;

            ChangeSignButton.BackColor = Color.FromArgb(0, 150, 136);
            ChangeSignButton.FlatStyle = FlatStyle.Flat;
            ChangeSignButton.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            ChangeSignButton.ForeColor = Color.White;
            ChangeSignButton.Location = new Point(246, 575);
            ChangeSignButton.Margin = new Padding(4, 5, 4, 5);
            ChangeSignButton.Name = "ChangeSignButton";
            ChangeSignButton.Size = new Size(107, 122);
            ChangeSignButton.TabIndex = 24;
            ChangeSignButton.Text = "+/-";
            ChangeSignButton.UseVisualStyleBackColor = false;
            ChangeSignButton.Click += FunctionButton_Click;

            SquareButton.BackColor = Color.FromArgb(0, 150, 136);
            SquareButton.FlatStyle = FlatStyle.Flat;
            SquareButton.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            SquareButton.ForeColor = Color.White;
            SquareButton.Location = new Point(360, 309);
            SquareButton.Margin = new Padding(4, 5, 4, 5);
            SquareButton.Name = "SquareButton";
            SquareButton.Size = new Size(107, 123);
            SquareButton.TabIndex = 25;
            SquareButton.Text = "x²";
            SquareButton.UseVisualStyleBackColor = false;
            SquareButton.Click += FunctionButton_Click;

            SquareRootButton.BackColor = Color.FromArgb(0, 150, 136);
            SquareRootButton.FlatStyle = FlatStyle.Flat;
            SquareRootButton.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            SquareRootButton.ForeColor = Color.White;
            SquareRootButton.Location = new Point(590, 177);
            SquareRootButton.Margin = new Padding(4, 5, 4, 5);
            SquareRootButton.Name = "SquareRootButton";
            SquareRootButton.Size = new Size(107, 123);
            SquareRootButton.TabIndex = 26;
            SquareRootButton.Text = "√";
            SquareRootButton.UseVisualStyleBackColor = false;
            SquareRootButton.Click += FunctionButton_Click;

            PercentButton.BackColor = Color.FromArgb(0, 150, 136);
            PercentButton.FlatStyle = FlatStyle.Flat;
            PercentButton.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            PercentButton.ForeColor = Color.White;
            PercentButton.Location = new Point(590, 310);
            PercentButton.Margin = new Padding(4, 5, 4, 5);
            PercentButton.Name = "PercentButton";
            PercentButton.Size = new Size(107, 122);
            PercentButton.TabIndex = 27;
            PercentButton.Text = "%";
            PercentButton.UseVisualStyleBackColor = false;
            PercentButton.Click += FunctionButton_Click;

            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(724, 715);
            Controls.Add(PercentButton);
            Controls.Add(SquareRootButton);
            Controls.Add(SquareButton);
            Controls.Add(ChangeSignButton);
            Controls.Add(DecimalButton);
            Controls.Add(MemoryRecallButton);
            Controls.Add(MemoryStoreButton);
            Controls.Add(TrigMenuButton);
            Controls.Add(SineButton);
            Controls.Add(EqualButton);
            Controls.Add(MultiplyButton);
            Controls.Add(DivideButton);
            Controls.Add(AddButton);
            Controls.Add(SubtractButton);
            Controls.Add(ClearButton);
            Controls.Add(Digit0Button);
            Controls.Add(Digit3Button);
            Controls.Add(Digit2Button);
            Controls.Add(Digit1Button);
            Controls.Add(Digit6Button);
            Controls.Add(Digit5Button);
            Controls.Add(Digit4Button);
            Controls.Add(Digit9Button);
            Controls.Add(Digit8Button);
            Controls.Add(Digit7Button);
            Controls.Add(DisplayLabel);
            Controls.Add(ExpressionLabel);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            Margin = new Padding(4, 5, 4, 5);
            MaximizeBox = false;
            Name = "CalculatorForm";
            Text = "Calculator";
            ResumeLayout(false);
        }

        public System.Windows.Forms.Label DisplayLabel;
        public System.Windows.Forms.Label ExpressionLabel;
        public RoundedButton Digit7Button;
        public RoundedButton Digit8Button;
        public RoundedButton Digit9Button;
        public RoundedButton Digit4Button;
        public RoundedButton Digit5Button;
        public RoundedButton Digit6Button;
        public RoundedButton Digit1Button;
        public RoundedButton Digit2Button;
        public RoundedButton Digit3Button;
        public RoundedButton Digit0Button;
        public RoundedButton ClearButton;
        public RoundedButton SubtractButton;
        public RoundedButton AddButton;
        public RoundedButton DivideButton;
        public RoundedButton MultiplyButton;
        public RoundedButton EqualButton;
        public RoundedButton SineButton;
        public RoundedButton TrigMenuButton;
        public RoundedButton MemoryStoreButton;
        public RoundedButton MemoryRecallButton;
        public RoundedButton DecimalButton;
        public RoundedButton ChangeSignButton;
        public RoundedButton SquareButton;
        public RoundedButton SquareRootButton;
        public RoundedButton PercentButton;
    }
}