// <auto-generated />
namespace PacmanGame.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FinalModelSetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FinalModelSetup));
        
        string IMigrationMetadata.Id
        {
            get { return "202512131604209_FinalModelSetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
